name: java-test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: compile code
      run: javac *.java
    - name: run tests
      run: java resolve google.com hshsd | if grep -q "Unable to resolve"; then echo "Test failed"; exit 1; else echo "Test passed"; fi