name: java-test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: compile code
        run: javac *.java
      - name: run tests on resolve
        run: java resolve google.com yelloelefant.com | grep -q "Unable to resolve" && echo "Test Failed" && exit 1 || echo "Test Passed" && exit 0
      - name: run tests on reverse
        run: java reverse 1.1.1.1 8.8.8.8 | grep -q "Unable to resolve" && echo "Test Failed" && exit 1 || echo "Test Passed" && exit 0
